types:
    BookmarkList:
        description: "List of bookmarked locations."
        type: object
        properties:
            totalCount:
                description: "The total number of bookmarks."
                type: integer
            items:
                description: "List of bookmarked locations."
                type: Location[]
    Location:
        description: "This class represents a location in the repository."
        type: object
        properties:
            id:
                description: "The id of the Location"
                type: integer
            status:
                description: "The status of the location. A location gets the status DRAFT = 0 on newly created content which is not published. When content is published the location gets the status STATUS_PUBLISHED = 1"
                type: integer
            priority:
                description: "Location priority. Position of the Location among its siblings when sorted using priority sort order."
                type: integer
            hidden:
                description: "Indicates that the Location entity has been explicitly marked as hidden."
                type: boolean
            invisible:
                description: "Indicates that the Location is implicitly marked as hidden by a parent Location."
                type: boolean
            remoteId:
                description: "Remote ID, universally unique identifier."
                type: string
            ContentInfo:
                description: "This class provides all version independent information of the Content object."
                type: class
            draft:
                description: "Returns true if current location is a draft."
                type: boolean
            parentLocationId:
                description: Parent ID.
                type: integer
            pathString:
                description: "The materialized path of the location entry e.g. /1/2/"
                type: string
            depth:
                description: Depth location has in the location tree.
                type: integer
            sortField:
                description: "Specifies which property the child locations should be sorted on. Map for Location sort fields to their respective SortClauses - class name/identifier and modified subnode. One of the fallowing values: const SORT_FIELD_PATH = 1; const SORT_FIELD_PUBLISHED = 2; const SORT_FIELD_MODIFIED = 3; const SORT_FIELD_SECTION = 4; const SORT_FIELD_DEPTH = 5; const SORT_FIELD_PRIORITY = 8; const SORT_FIELD_NAME = 9; const SORT_FIELD_NODE_ID = 11; const SORT_FIELD_CONTENTOBJECT_ID = 12;"
                type: integer
            sortOrder:
                description: "Specifies whether the sort order should be ascending or descending. Map for Location sort order to their respective Query SORT constants. One of the fallowing values: const SORT_ORDER_DESC = 0; const SORT_ORDER_ASC = 1"
                type: integer
            Content:
                description: "Represents a content object in a specific version"
                type: Content
    Content:
        description: "Content Id matcher class"
        type: object
        properties:
            getVersionInfo:
                description: "Returns the VersionInfo for this version."
                type: VersionInfo
            getName:
                description: "Shorthand method for getVersionInfo()->getName(). Return the name of the domain object in a given language."
                type: string
            getFieldValue:
                description: "Returns a field value for the given value."
                type: string
            getFields:
                description: "This method returns the complete fields collection."
                type: Field[]
            getFieldsByLanguage:
                description: "This method returns the fields for a given language and non translatable fields."
                type: Field[]
            getField:
                description: "This method returns the field for a given field definition identifier and language."
                type: Field
            getContentType:
                descritpion: "Content Type value"
                type: ContentType
    ContentType:
        descritpion: "Content Type"
        type: object
        properties:
            id:
                description: "Content type ID."
                type: integer
            status:
                description: "The status of the content type. Possible values: const STATUS_DEFINED = 0; Status constant for defined (aka published) Type, const STATUS_DRAFT = 1; Status constant for draft (aka temporary) Type; const STATUS_MODIFIED = 2; Status constant for modified (aka deferred for publishing) Type"
                type: integer
            identifier:
                description: "String identifier of a content type."
                type: string
            creationDate:
                description: "Creation date of the content type."
                type: DateTime
            modificationDate:
                description: "Modification date of the content type."
                type: DateTime
            creatorId:
                descritpion: "Creator user id of the content type."
                type: integer
            modifierId:
                description: "Modifier user id of the content type."
                type: integer
            remoteId:
                description: "Unique remote ID of the content type."
                type: string
            urlAliasSchema:
                description: "URL alias schema. If nothing is provided, $nameSchema will be used instead."
                type: string
            nameSchema:
                description: "Name schema. Can be composed of FieldDefinition identifier place holders."
                type: string
            isContainer:
                description: "A flag used to hint if content of this type may have children or not. It is highly recommended to respect this flag and not create/move content below non-containers. But this flag is not considered as part of the content model and the API will not in any way enforce this flag to be respected."
                type: boolean
            defaultAlwaysAvailable:
                description: "If an instance of a content type is created the always available flag is set by default to this value."
                type: boolean
            defaultSortField:
                descritpion: "Specifies which property the child locations should be sorted on by default when created. Map for Location sort fields to their respective SortClauses - class name/identifier and modified subnode. One of the fallowing values: const SORT_FIELD_PATH = 1; const SORT_FIELD_PUBLISHED = 2; const SORT_FIELD_MODIFIED = 3; const SORT_FIELD_SECTION = 4; const SORT_FIELD_DEPTH = 5; const SORT_FIELD_PRIORITY = 8; const SORT_FIELD_NAME = 9; const SORT_FIELD_NODE_ID = 11; const SORT_FIELD_CONTENTOBJECT_ID = 12;"
                    type: integer
            defaultSortOrder:
                description: "Specifies whether the sort order should be ascending or descending by default when created. Map for Location sort order to their respective Query SORT constants. Possible values: const SORT_ORDER_DESC = 0; const SORT_ORDER_ASC = 1"
                type: integer
            languageCodes:
                description: "List of language codes used by translations."
                type: string
            getContentTypeGroups:
                description: "This method returns the content type groups this content type is assigned to."
                type: ContentTypeGroup[]
            getFieldDefinitions:
                description: "This method returns the content type field definitions from this type."
                type: FieldDefinition[]
            getFieldDefinition:
                description: "This method returns the field definition for the given identifier."
                type: FieldDefinition
    ContentInfo:
        description: "This class provides all version independent information of the Content object."
        type: object
        properties:
            id:
                description: "The unique id of the Content object."
                type: integer
            contentTypeId:
                description: "The Content Type id of the Content object."
                type: integer
            name:
                description: "The computed name (via name schema) in the main language of the Content object."
                type: string
            sectionId:
                description: "The section to which the Content object is assigned."
                type: integer
            currentVersionNo:
                description: "Current Version number is the version number of the published version or the version number of a newly created draft (which is 1)."
                type: integer
            published:
                description: "True if there exists a published version, false otherwise."
                type: boolean
            ownerId:
                description: "The owner of the Content object."
                type: integer
            modificationDate:
                description: "Content modification date."
                type: DateTime
            publishedDate:
                description: "Content publication date."
                type: DateTime
            alwaysAvailable:
                description: "Indicates if the Content object is shown in the main language if its not present in an other requested language."
                type: boolean
            remoteId:
                description: "Remote identifier used as a custom identifier for the object."
                type: string
            mainLanguageCode:
                description: "The main language code of the Content object."
                type: string
            mainLocationId:
                description: "Identifier of the main location. If the Content object has multiple locations, mainLocationId will point to the main one."
                type: integer
            status:
                description: "Status of the content. Possible values: const STATUS_DRAFT = 0;const STATUS_PUBLISHED = 1; const STATUS_TRASHED = 2"
                type: integer
    ContentTypeGroup:
        description: "This class represents a content type group value."
        type: object
        properties:
            id:
                description: "Primary key."
                type: integer
            identifier:
                description: "Readable string identifier of a group."
                type: string
            creationDate:
                description: "Created date (timestamp)."
                type: DateTime
            modificationDate:
                description: "Modified date (timestamp)."
                type: DateTime
            creatorId:
                description: "Creator user id."
                type: integer
            modifierId:
                description: "Modifier user id."
                type: integer
    FieldDefinition:
        description: "This class represents a field definition."
        type: object
        properties:
            id:
                description: "The unique id of this field definition."
                type: integer
            identifier:
                description: "Readable string identifier of a field definition."
                type: string
            fieldGroup:
                description: "Field group name."
                type: string
            position:
                description: "The position of the field definition in the content type."
                type: integer
            fieldTypeIdentifier:
                description: "String identifier of the field type."
                type: string
            isTranslatable:
                description: "If the field is translatable."
                type: boolean
            isRequired:
                description: "Is the field required."
                type: boolean
            isInfoCollector:
                description: "The flag if this field is used for information collection."
                type: boolean
            ValidatorConfiguration:
                description: "This method returns the validator configuration of this field definition supported by the field type."
                type: any
            FieldSettings:
                description: "This method returns settings for the field definition supported by the field type."
                type: any
            defaultValue:
                description: "Default value of the field."
                type: any
            isSearchable:
                description: "Indicates if th the content is searchable by this attribute."
                type: boolean
            mainLanguageCode:
                description: "Based on mainLanguageCode of contentType."
                type: string
    Field:
        description: "This class represents a field of a content object."
        type: object
        properties:
            id:
                description: "The field id."
                type: integer
            fieldDefIdentifier:
                description: "The field definition identifier."
                type: string
            value:
                description: "A field type value or a value type which can be converted by the corresponding field type."
                type: any
            languageCode:
                description: "The language code."
                type: string
            fieldTypeIdentifier:
                description: "Field type identifier."
                type: string
    DateTime: TODO Ask Adam
        description: "Representation of date and time."
        type: object
        properties:
            construct:
    VersionInfo:
        description: "This class holds version information data. It also contains the corresponding {@link Content} to which the version belongs to."
        type: object
        properties:
            id:
                description: "Version ID."
                type: integer
            versionNo:
                description: "Version number. In contrast to {@link $id}, this is the version number, which only increments in scope of a single Content object."
                type: integer
            getContentInfo:
                description: "Content of the content this version belongs to."
                type: ContentInfo
            modificationDate:
                description: "The last modified date of this version."
                type: DateTime
            creatorId:
                description: "Creator user ID. Creator of the version, in the search API this is referred to as the modifier of the published content."
                type: integer
            creationDate:
                description: "Content creation date."
                type: DateTime
            status:
                description: "One of: VersionInfo::STATUS_DRAFT=0, VersionInfo::STATUS_PUBLISHED=1, VersionInfo::STATUS_ARCHIVED=3."
                type: integer
            initialLanguageCode:
                description: "The language code which is used for labeling a translation."
                type: string
            languageCodes:
                description: "List of languages in this version. Reflects which languages fields exists in for this version."
                type: string[]
            isDraft:
                description: "Returns true if version is a draft. Returns status self::STATUS_DRAFT."
                type: boolean
            isPublished:
                description: "Returns true if version is published. Returns status self::STATUS_PUBLISHED"
                type: boolean
            isArchived:
                description: "Returns true if version is archived. Returns status self::STATUS_ARCHIVED"
                type: boolean
