#%RAML 1.0
---
title: eZ Platform API documentation (Test)
version: 2.4


ContentService:
    description: This class provides service methods for managing content.
    example: Examples/content.php
    parameters:
        loadContentInfo:
            description: Loads a content info object. To load fields use loadContent
        loadContentInfoList:
            description:
        loadContentInfoByRemoteId:
        loadVersionInfo:
